### ISSUE TITLE
kicked when using mod

### ISSUE THREAD

**Issue by MommyChillz** [Gurge44/TOHE_PLUS#6]
When i get into a game using the same mod as host TOHE+ v1.4.0 i get kicked when game has started im not sure if thats meant to happen but i wasnt sure

**Comment by Gurge44** [comment]
I need a log file and a lot more info about what happened. Were you host or a modded client? What was the disconnect message? When exactly did you get kicked, when the game started or after joining the lobby? Did the game say you have an incompatible version? What version of Among Us do you have?

**Comment by MommyChillz** [comment]
do you know how i can get logs?
and message was just you were kicked can rejoin later 
i was not the host

**Comment by Gurge44** [comment]
If you didn't open Among Us since this happened, there should be a file located in **Among Us/BepInEx/LogOutput.log**. Send me that file.

**Comment by Gurge44** [comment]
Though, the host likely had a level restriction you didn't meet, but let's see.

**Comment by MommyChillz** [comment]
ill see if i can rejoin and check it again bc i have opened among us since

**Comment by MommyChillz** [comment]
[LogOutput.log](https://github.com/Gurge44/TOHE_PLUS/files/13463611/LogOutput.log)

**Comment by MommyChillz** [comment]
i got kicked again

**Comment by Gurge44** [comment]
So you were in the lobby for 5 minutes then got disconnected?

**Comment by MommyChillz** [comment]
So i dont remember how long but i got kicked when the game had told me my role and everything.

**Comment by Gurge44** [comment]
So, for now, I think it's best to not join on a non-host modded client, it has various known issues during the game as well. I recommend you join on a vanilla client, and if you don't want to uninstall the mod to do that, you can simply go into the settings > TOHE Options > Click "Switch Vanilla" while on the main menu screen.

The cause is unknown as the log says that the disconnect reason is "ExitGame" which is when the player manually leaves the game.

**Comment by MommyChillz** [comment]
ok ty

**Comment by MommyChillz** [comment]
i just realised i sent the wrong log i have so many tohe thing i thought i sent you the right one im so sorry for wasting your time

**Comment by MommyChillz** [comment]
[LogOutput.log](https://github.com/Gurge44/TOHE_PLUS/files/13463657/LogOutput.log)
this is the right one if you want to look u might have to scroll up a tad bit but for now i dont mind sorry thats my fault

**Comment by Gurge44** [comment]
You have no friend code, that's why you were kicked.
**[Info   :      TOHE] [10:08:08][Session]China - (ClientID: 225121 / FriendCode: ) - Disconnected: Kicked，Ping: (48)**

Log in properly and this won't happen. Hosts have an option to kick players without friend codes since they're most likely hackers.

**Comment by Gurge44** [comment]
Or your network / device is weak. Those are the two possible causes.

**Comment by MommyChillz** [comment]
oh i see

**Comment by MommyChillz** [comment]
sorry for that ty
